# Generated by Django 4.2.7 on 2024-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_organizationalmember_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalmember',
            name='image',
            field=models.ImageField(default={}, upload_to='images'),
            preserve_default=False,
        ),
    ]
