# Generated by Django 5.1.3 on 2024-12-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_organizationalmember_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalmember',
            name='image',
        ),
        migrations.RemoveField(
            model_name='organizationalmember',
            name='parent',
        ),
        migrations.AddField(
            model_name='organizationalmember',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='home.organizationalmember'),
        ),
    ]
