# Generated by Django 5.1.3 on 2024-12-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_organizationalmember_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalmember',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
